'use client';
import Link from 'next/link';
import { ArrowRight, BarChart3, Brush, Code2, Mail, Megaphone, PenLine, SearchCheck, ShieldCheck, Sparkles, Target, Users, Video, Wrench } from 'lucide-react';
import CtaBanner from '@/components/shared/CtaBanner';
import ServiceFaq from '@/components/shared/ServiceFaq';
import './DigitalMarketing.css';

const groups = [
  ['Demand & Lead Generation', 'Generate relevant traffic, enquiries, and potential customers.', [['Paid Advertising','Reach the right audience with targeted campaigns.','paid-advertising',Megaphone],['SEO','Improve search visibility and attract active customers.','seo',SearchCheck],['Email Marketing','Nurture prospects and customers with targeted campaigns.','email-marketing',Mail],['Conversion Rate Optimization','Turn more visitors into enquiries.','conversion-rate-optimization',BarChart3]]],
  ['Social & Growth', 'Stay visible, relevant, and trusted online.', [['Social Media Marketing','Build an active social presence with consistent engagement.','social-media-marketing',Users],['Online Reputation Management','Maintain a credible and positive digital presence.','online-reputation-management',ShieldCheck]]],
  ['Content Services', 'Build authority and communicate your value.', [['Content Writing Services','Create clear content for every digital channel.','content-writing-services',PenLine],['Content Marketing Services','Plan and distribute content to attract your audience.','content-marketing-services',Sparkles]]],
  ['Website Support', 'Make sure your website keeps performing.', [['Website Development','Create responsive websites around your customer journey.','website-development',Code2],['Website Maintenance & Management','Keep your website secure, updated, and fast.','website-maintenance-management',Wrench]]],
  ['Digital Events', 'Turn podcasts and webinars into growth opportunities.', [['Podcast Marketing','Build awareness and engagement around your podcast.','podcast-marketing',Video],['Webinar Marketing','Attract the right audience and increase registrations.','webinar-marketing',Megaphone]]],
  ['Creative Designing', 'Communicate clearly and consistently with strong creative.', [['Graphics Designing','Create professional, on-brand graphics for every platform.','graphics-designing',Brush],['Video Editing Services','Transform footage into polished marketing videos.','video-editing-services',Video]]],
];

export default function DigitalMarketingPage() { return <main className="growth-page digital-marketing-page"><section className="growth-hero"><div className="container"><span className="growth-eyebrow">Digital Marketing Services</span><h1>Marketing That Gives You Growth, Not Just More Work</h1><p>Build a stronger digital presence, reach the right audience, and turn more opportunities into business with Proowrx&apos;s end-to-end digital marketing services.</p><Link className="btn btn-gold" href="/contact">Get Started Now <ArrowRight size={15}/></Link></div></section><section className="growth-section"><div className="container"><div className="growth-head"><span className="chip chip-gold">Everything You Need to Grow Online</span><h2>One integrated digital marketing team</h2><p>Strategy, execution, creative, and ongoing support work together without the overhead of building a large in-house team.</p></div><div className="growth-grid">{groups.map(([title,intro,items])=><article className="growth-card" key={title}><div className="growth-card-header"><div className="growth-card-icon"><Target size={22}/></div><h3>{title}</h3></div><p>{intro}</p><Link className="growth-inline-link" href={`/digital-marketing/${items[0][2]}`}>Explore services <ArrowRight size={14}/></Link></article>)}</div></div></section><section className="growth-section alt"><div className="container"><div className="growth-head"><span className="chip chip-teal">Our Suite of Services</span><h2>Choose the right combination for your goals</h2></div>{groups.map(([title,intro,items])=><div className="growth-service-group" key={title}><div className="growth-service-group-head"><h3>{title}</h3><p>{intro}</p></div><div className="growth-grid">{items.map(([name,text,slug,Icon])=><Link className="growth-card" href={`/digital-marketing/${slug}`} key={slug}><div className="growth-card-header"><div className="growth-card-icon"><Icon size={22}/></div><h3>{name}</h3></div><p>{text}</p><span className="growth-inline-link">View service <ArrowRight size={14}/></span></Link>)}</div></div>)}</div></section><section className="growth-section"><div className="container growth-split"><div className="growth-copy"><span className="chip chip-gold">One Team. Multiple Capabilities.</span><h2>Strategy → Creation → Execution → Optimization → Growth</h2><p>Whether you need one specific service or a complete digital marketing solution, we build the right combination around your requirements.</p><ul className="growth-list growth-list--lucide"><li><ShieldCheck size={16}/>Industry-focused understanding</li><li><ShieldCheck size={16}/>Clear communication and approvals</li><li><ShieldCheck size={16}/>Flexible outsourcing model</li><li><ShieldCheck size={16}/>Coordinated execution across channels</li></ul></div></div></section><ServiceFaq variant="digitalMarketing" title="Digital marketing support questions" intro="What businesses commonly ask before outsourcing marketing execution."/><CtaBanner/></main>; }
