import { ArrowRight } from 'lucide-react';
import CtaBanner from '@/components/shared/CtaBanner';
import ServiceFaq from '@/components/shared/ServiceFaq';
import '../GrowthPages.css';

export const metadata={title:'Digital Marketing Support Services',description:'Outsourced digital marketing support for Australian mortgage brokers, accountants and finance businesses—content, social media, SEO, email campaigns and reporting.',keywords:['digital marketing outsourcing Australia','mortgage broker marketing support','accounting firm digital marketing','SEO content support','social media virtual assistant'],alternates:{canonical:'/digital-marketing'},openGraph:{title:'Digital Marketing Support for Finance Businesses | Proowrx',description:'Consistent, practical marketing execution for mortgage, accounting and finance brands.',url:'/digital-marketing'}};
const capabilities=[['✍️','Content Production','Website copy, educational articles, newsletters and campaign content aligned with your brand.'],['📱','Social Media Support','Content calendars, post preparation, scheduling and community-response workflows.'],['🔎','SEO Assistance','Keyword research, on-page optimisation, content briefs and performance-led improvements.'],['📧','Email Campaigns','Newsletter production, audience segmentation and automated nurture-sequence support.'],['🎨','Creative Coordination','Branded graphics, campaign assets and consistent visual content production.'],['📈','Reporting & Insights','Clear monthly reporting across traffic, engagement, leads and content performance.']];
export default function DigitalMarketingPage(){return <main className="growth-page"><section className="growth-hero"><div className="container">
    <span className="growth-eyebrow">Digital Marketing Services</span>
    <h1>Consistent marketing without expanding your local team</h1>
    <p>Build a dependable marketing rhythm with trained remote support for content, social media, SEO, email campaigns and reporting—tailored to finance-sector businesses.</p>
    {/* <div className="growth-actions">
        <a className="btn btn-gold" href="https://calendly.com/proowrx/30min" target="_blank" rel="noreferrer">Book a Meeting <ArrowRight size={15}/></a></div> */}
        </div></section><section className="growth-section"><div className="container"><div className="growth-head"><span className="chip chip-gold">Marketing Execution</span><h2>The support needed to stay visible</h2><p>Turn your strategy into repeatable weekly action while your advisers and client-facing team stay focused on customers.</p></div><div className="growth-grid">{capabilities.map(([icon,title,text])=><article className="growth-card" key={title}><div className="growth-card-icon">{icon}</div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><section className="growth-section alt"><div className="container growth-split"><div className="growth-copy"><span className="chip chip-teal">Your Brand, Your Process</span><h2>A remote marketing extension—not a disconnected supplier</h2><p>We work from your approved messaging, compliance process, brand guidelines and campaign plan. Tasks can be delivered through a dedicated part-time resource, a full-time marketing assistant or a broader specialist team.</p><ul className="growth-list"><li>Mortgage broker and accounting industry context</li><li>Documented approval and publishing workflows</li><li>Consistent brand and compliance checks</li><li>Flexible capacity as campaigns expand</li></ul></div><div className="growth-metrics"><div className="growth-metric"><strong>SEO</strong><span>Search-led content support</span></div><div className="growth-metric"><strong>Social</strong><span>Consistent channel activity</span></div><div className="growth-metric"><strong>Email</strong><span>Client nurture campaigns</span></div><div className="growth-metric"><strong>Reports</strong><span>Actionable performance insights</span></div></div></div></section><ServiceFaq variant="digitalMarketing" title="Digital marketing support questions" intro="What finance businesses commonly ask before outsourcing marketing execution."/><CtaBanner/></main>}
